name: ${project.name}
main: net.azisaba.namechange.NameChangeAutomation
version: ${project.version}
author: siloneco,Arisa9006,matsu1213
description: ${project.description}
website: ${project.url}
depend: ["CrackShot", "CrackShotPlus", "LeonCSAddon"]
api-version: 1.16
commands:
  namechange:
    permission: namechangeautomation.command.namechange
  namechangereload:
    permission: namechangeautomation.command.namechange
permissions:
  namechangeautomation.command.namechange:
    default: op