name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - "**.md"
      - "renovate.json"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'adopt'
          server-id: azisaba
      - name: Check CrackShot existence
        id: check_crackshot
        uses: andstor/file-existence-action@v3
        with:
          files: "/home/runner/.m2/repository/com/shampaggon/CrackShot/0.98.11/CrackShot-0.98.11.pom"
      - name: Download CrackShot v0.98.11
        if: steps.check_crackshot.outputs.files_exists == 'false'
        run: curl -L -o CrackShot.jar https://dev.bukkit.org/projects/crackshot/files/3151915/download
      - name: Install CrackShot into local mvn repo
        if: steps.check_crackshot.outputs.files_exists == 'false'
        run: mvn install:install-file -Dfile=./CrackShot.jar -DgroupId=com.shampaggon -DartifactId=CrackShot -Dversion=0.98.11 -Dpackaging=jar -DgeneratePom=true
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Prepare settings.xml
        run: |
          echo "<settings><servers><server><id>azisaba</id><username>${{ secrets.REPO_USERNAME }}</username><password>${{ secrets.REPO_PASSWORD }}</password></server></servers></settings>" > $HOME/.m2/settings.xml
      - name: Deploy
        run: mvn deploy
